version: '3.9'

services:
  warehouse:
    image: postgres:15
    container_name: warehouse
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    platform: linux/amd64

  pipelinerunner:
    image: pipelinerunner
    container_name: pipelinerunner
    build:
      context: ./
      dockerfile: ./containers/pipelinerunner/Dockerfile
    volumes:
      - ./:/code
    environment:
      WAREHOUSE_USER: ${POSTGRES_USER}
      WAREHOUSE_PASSWORD: ${POSTGRES_PASSWORD}
      WAREHOUSE_DB: ${POSTGRES_DB}
      WAREHOUSE_HOST: ${POSTGRES_HOST}
      WAREHOUSE_PORT: ${POSTGRES_PORT}
    platform: linux/amd64

  dashboard:
    image: metabase/metabase
    container_name: dashboard
    ports:
      - "3000:3000"
    platform: linux/amd64
